apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: mongo
  name: mongo
  namespace: products-store
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.mongo: semver:~4.0.24 # fluxcd.io/tag.<container-name>: <filter-type>:<filter-value>
spec:
  replicas: 1
  selector:
    matchLabels:
      service: mongo
  strategy: {}
  template:
    metadata:
      labels:
        service: mongo
    spec:
      containers:
        - image: mongo:4.0.24
          name: mongo
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
