apiVersion: v1
kind: Service
metadata:
  labels:
    service: mongo
  name: redis
  namespace: products
spec:
  ports:
    - name: "redis-port"
      port: 6379
      targetPort: 6379
  selector:
    service: redis
status:
  loadBalancer: {}
